import { TippingElementMetadata } from "@/types/api";

export const TIPPING_ELEMENTS: TippingElementMetadata[] = [
  {
    id: "amoc",
    name: "Atlantic Meridional Overturning Circulation (AMOC)",
    shortName: "AMOC Slowdown",
    region: "North Atlantic Ocean",
    coordinates: [53.0, -35.0],
    riskScore: 0.68,
    tempAnomaly: -1.2, // Cold blob anomaly
    oceanCirculationAnomaly: -18.5, // % slowdown vs historical baseline
    confidenceScore: 0.89,
    leadTimeMonths: 14,
    status: "WARNING",
    description: "The system of ocean currents carrying warm water from the tropics into the North Atlantic. Critical slowing down is evidenced by increased variance and rising Lag-1 autocorrelation in RAPID-MOCHA transport time series.",
    importantVariables: ["moc_transports", "florida_current", "ekman_transport", "upper_mid_ocean", "sea_surface_salinity"],
    recentAnomalies: "Persistent North Atlantic cold blob accompanied by a 3.2 Sv reduction in southward deep water transport over the last 24 months.",
    supportingDatasets: ["RAPID-MOCHA-WBTS (26.5°N)", "OSNAP Array (53°-60°N)", "ECMWF ERA5 SST Reanalysis", "CMIP6 Abrupt-4xCO2 Simulations"],
    historicalTrend: [
      { year: 2004, val: 19.8, anomaly: 0.2 },
      { year: 2008, val: 18.9, anomaly: -0.7 },
      { year: 2012, val: 17.5, anomaly: -2.1 },
      { year: 2016, val: 17.1, anomaly: -2.5 },
      { year: 2020, val: 16.4, anomaly: -3.2 },
      { year: 2024, val: 15.8, anomaly: -3.8 },
    ],
  },
  {
    id: "amazon",
    name: "Amazon Rainforest Dieback",
    shortName: "Amazon Dieback",
    region: "Amazon Basin, South America",
    coordinates: [-3.46, -62.21],
    riskScore: 0.54,
    tempAnomaly: 1.8,
    vegetationLoss: 14.2,
    confidenceScore: 0.85,
    leadTimeMonths: 28,
    status: "WATCH",
    description: "Non-linear transition of rainforest savanna ecosystems due to deforestation, moisture recycling failure, and lengthened dry seasons.",
    importantVariables: ["evi_anomaly", "ndwi_moisture", "vapor_pressure_deficit", "canopy_temperature", "precipitation_deficit"],
    recentAnomalies: "Extreme 2023-2024 drought induced record-low river stages and widespread loss of resilience across southern Amazon sub-basins.",
    supportingDatasets: ["NASA MODIS MCD43A4 NBAR", "CHIRPS v2.0 Precipitation", "SMAP Soil Moisture", "ESA CCI Land Cover"],
    historicalTrend: [
      { year: 2004, val: 86.5, anomaly: 1.2 },
      { year: 2008, val: 84.1, anomaly: -1.2 },
      { year: 2012, val: 83.0, anomaly: -2.3 },
      { year: 2016, val: 80.4, anomaly: -4.9 },
      { year: 2020, val: 77.2, anomaly: -8.1 },
      { year: 2024, val: 73.8, anomaly: -11.5 },
    ],
  },
  {
    id: "greenland",
    name: "Greenland Ice Sheet Collapse",
    shortName: "Greenland Ice Sheet",
    region: "Greenland / Arctic",
    coordinates: [72.0, -40.0],
    riskScore: 0.74,
    tempAnomaly: 2.6,
    iceLossRate: 275.4, // Gt/yr
    confidenceScore: 0.92,
    leadTimeMonths: 9,
    status: "WARNING",
    description: "Accelerated surface melt and marine-terminating glacier retreat governed by melt-elevation feedback (lapse rate feedback) and basal lubrication.",
    importantVariables: ["mass_anomaly_gt", "surface_melt_area", "albedo_reduction", "outlet_glacier_velocity", "firn_air_depletion"],
    recentAnomalies: "Summer 2023 melt extent reached the 98th historical percentile, with record mass loss across the Jakobshavn Isbræ drainage basin.",
    supportingDatasets: ["NASA GRACE / GRACE-FO Monthly Mascons", "NSIDC MEaSUREs Velocity", "RACMO2.3p2 Regional Climate Model", "MODIS MOD10A1 Albedo"],
    historicalTrend: [
      { year: 2004, val: 0.0, anomaly: -120 },
      { year: 2008, val: -850.0, anomaly: -970 },
      { year: 2012, val: -2100.0, anomaly: -2220 },
      { year: 2016, val: -3200.0, anomaly: -3320 },
      { year: 2020, val: -4350.0, anomaly: -4470 },
      { year: 2024, val: -5450.0, anomaly: -5570 },
    ],
  },
  {
    id: "coral",
    name: "Tropical Coral Reef Bleaching",
    shortName: "Coral Reef Bleaching",
    region: "Great Barrier Reef / Caribbean",
    coordinates: [-18.28, 147.7],
    riskScore: 0.88,
    tempAnomaly: 1.95,
    confidenceScore: 0.96,
    leadTimeMonths: 3,
    status: "CRITICAL",
    description: "Mass mortality of reef-building scleractinian corals triggered by marine heatwaves exceeding thermal tolerance thresholds (Degree Heating Weeks > 8 °C-weeks).",
    importantVariables: ["degree_heating_weeks", "sea_surface_temp_anomaly", "bleaching_alert_area", "par_irradiance", "aragonite_saturation"],
    recentAnomalies: "Fourth global coral bleaching event currently underway; DHW values exceeded 12 °C-weeks across 73% of equatorial reef sectors.",
    supportingDatasets: ["NOAA Coral Reef Watch Daily 5km v3.1", "CoralNet Automated Benthic Surveys", "Allen Coral Atlas", "GHRSST L4 SST Reanalysis"],
    historicalTrend: [
      { year: 2004, val: 1.2, anomaly: 0.3 },
      { year: 2008, val: 2.1, anomaly: 1.2 },
      { year: 2012, val: 3.5, anomaly: 2.6 },
      { year: 2016, val: 7.8, anomaly: 6.9 },
      { year: 2020, val: 6.4, anomaly: 5.5 },
      { year: 2024, val: 11.6, anomaly: 10.7 },
    ],
  },
  {
    id: "sea_ice",
    name: "Arctic Summer Sea Ice Loss",
    shortName: "Arctic Sea Ice",
    region: "Arctic Ocean / Beaufort Sea",
    coordinates: [82.0, -140.0],
    riskScore: 0.61,
    tempAnomaly: 3.4, // Arctic amplification
    confidenceScore: 0.88,
    leadTimeMonths: 18,
    status: "WATCH",
    description: "Transition to a seasonally ice-free Arctic Ocean driven by ice-albedo positive feedback and increased ocean heat convergence from the North Atlantic.",
    importantVariables: ["sea_ice_extent", "sea_ice_thickness", "albedo_feedback_coeff", "transpolar_drift_speed", "surface_net_radiation"],
    recentAnomalies: "September minimum sea ice volume remains 48% below the 1979-2000 climatological mean, with multi-year ice virtually vanishing in peripheral seas.",
    supportingDatasets: ["NSIDC Sea Ice Index v3", "ESA CryoSat-2 Ice Thickness", "PIOMAS Assimilation Model", "ERA5 Arctic Reanalysis"],
    historicalTrend: [
      { year: 2004, val: 6.05, anomaly: -0.85 },
      { year: 2008, val: 4.73, anomaly: -2.17 },
      { year: 2012, val: 3.63, anomaly: -3.27 },
      { year: 2016, val: 4.14, anomaly: -2.76 },
      { year: 2020, val: 3.92, anomaly: -2.98 },
      { year: 2024, val: 4.08, anomaly: -2.82 },
    ],
  },
];
