import { ModelSpecification } from "@/types/api";

export const MODEL_ZOO: ModelSpecification[] = [
  {
    id: "temporal_fusion_transformer",
    name: "Temporal Fusion Transformer (TFT)",
    category: "Transformer",
    description: "State-of-the-art multi-horizon attention architecture incorporating Variable Selection Networks (VSNs), Gated Residual Networks (GRNs), and static metadata enrichment.",
    parameters: "3.2M",
    latencyMs: 42.5,
    rocAuc: 0.984,
    prAuc: 0.962,
    f1Score: 0.951,
    leadTimeAccuracy: "94.2% (±1.5 mo)",
    architectureDetails: [
      "Variable Selection Network for pruning noisy input drivers",
      "Gated Residual Network with ELU activation and layer normalization",
      "Interpretable Multi-Head Self-Attention over temporal sequences",
      "Quantile regression output heads (0.1, 0.5, 0.9) for uncertainty bounds",
    ],
    hyperparameters: { hidden_dim: 256, n_heads: 4, n_layers: 3, dropout: 0.1, lr: 0.0001, epochs: 50 },
  },
  {
    id: "informer",
    name: "Informer (ProbSparse Attention)",
    category: "Transformer",
    description: "Efficient long-sequence time-series forecasting transformer utilizing ProbSparse self-attention and generative decoder distilling to achieve O(L log L) time and space complexity.",
    parameters: "4.8M",
    latencyMs: 38.1,
    rocAuc: 0.971,
    prAuc: 0.948,
    f1Score: 0.938,
    leadTimeAccuracy: "91.8% (±2.1 mo)",
    architectureDetails: [
      "ProbSparse self-attention mechanism filtering inactive queries",
      "Self-attention distilling operations halving cascading layer length",
      "Generative inference decoder predicting long horizons in a single forward pass",
    ],
    hyperparameters: { d_model: 512, n_heads: 8, e_layers: 3, d_layers: 2, factor: 5, dropout: 0.05 },
  },
  {
    id: "time_series_transformer",
    name: "Time-Series Transformer (Vanilla + CLS)",
    category: "Transformer",
    description: "Standard encoder-only transformer adapted for continuous geospatial time series with learnable sinusoidal positional encodings and a dedicated classification token head.",
    parameters: "2.1M",
    latencyMs: 28.4,
    rocAuc: 0.965,
    prAuc: 0.939,
    f1Score: 0.925,
    leadTimeAccuracy: "89.5% (±2.4 mo)",
    architectureDetails: [
      "Pre-LayerNorm multi-head self-attention encoder stack",
      "Learnable temporal embedding combined with feature projection",
      "Additive attention pooling over sequence tokens for classification",
    ],
    hyperparameters: { d_model: 128, n_heads: 4, num_layers: 4, dim_feedforward: 512, dropout: 0.1 },
  },
  {
    id: "climate_gnn",
    name: "Climate Spatial GNN (GCN / SAGE)",
    category: "GNN",
    description: "Graph Neural Network capturing complex teleconnections and spatial moisture/heat transport across global climate grid cells via message passing over k-NN correlation graphs.",
    parameters: "1.8M",
    latencyMs: 34.2,
    rocAuc: 0.978,
    prAuc: 0.955,
    f1Score: 0.944,
    leadTimeAccuracy: "92.7% (±1.8 mo)",
    architectureDetails: [
      "Dynamic k-NN spatial adjacency graph construction from lat/lon grids",
      "GraphSAGE inductive neighborhood aggregation with mean/max pooling",
      "Global attention readout layer mapping graph states to tipping risk",
    ],
    hyperparameters: { in_channels: 16, hidden_channels: 128, num_layers: 3, k_neighbors: 8, dropout: 0.15 },
  },
  {
    id: "dynamic_graph_network",
    name: "Dynamic Temporal GNN (T-GCN)",
    category: "GNN",
    description: "Hybrid spatial-temporal neural architecture coupling Graph Convolutional Networks with Gated Recurrent Units (GRUs) to model evolving climate network topology over time.",
    parameters: "2.5M",
    latencyMs: 51.0,
    rocAuc: 0.981,
    prAuc: 0.959,
    f1Score: 0.949,
    leadTimeAccuracy: "93.5% (±1.6 mo)",
    architectureDetails: [
      "Spatial Graph Convolution evaluating localized grid cell interactions",
      "Temporal GRU cell tracking historical state transitions across time steps",
      "End-to-end joint optimization for spatio-temporal early warning signals",
    ],
    hyperparameters: { node_features: 12, hidden_dim: 128, seq_len: 24, rnn_layers: 2, lr: 0.0002 },
  },
  {
    id: "physics_informed_nn",
    name: "Physics-Informed NN (PINN)",
    category: "Physics & Causal",
    description: "Deep neural network embedding thermodynamic Navier-Stokes and energy balance differential equations directly into the loss function via automatic differentiation residuals.",
    parameters: "950K",
    latencyMs: 22.1,
    rocAuc: 0.989,
    prAuc: 0.974,
    f1Score: 0.966,
    leadTimeAccuracy: "96.8% (±1.1 mo)",
    architectureDetails: [
      "Multi-layer perceptron with sinusoidal activation functions",
      "PDE residual loss term penalizing violations of conservation of mass/energy",
      "Physics-constrained boundary conditions ensuring physical realism",
    ],
    hyperparameters: { layers: [8, 64, 64, 64, 1], lambda_pde: 0.25, optimizer: "L-BFGS + AdamW" },
  },
  {
    id: "pcmci_causal",
    name: "PCMCI Non-Linear Causal Discovery",
    category: "Physics & Causal",
    description: "Tigramite-powered causal discovery algorithm utilizing condition-selection PC algorithm followed by Moment-Conditioned Conditional Independence (MCI) testing.",
    parameters: "N/A (Algorithmic)",
    latencyMs: 120.0,
    rocAuc: 0.952,
    prAuc: 0.921,
    f1Score: 0.910,
    leadTimeAccuracy: "88.0% (±2.8 mo)",
    architectureDetails: [
      "PC1 phase removing spurious autocorrelation correlations",
      "MCI phase testing conditional independence on parent Markov sets",
      "Constructs empirical causal graphs with time-lagged directional arrows",
    ],
    hyperparameters: { tau_max: 6, pc_alpha: 0.05, test: "ParCorr / CMIknn" },
  },
  {
    id: "arima_baseline",
    name: "AR(1) Critical Slowing Down Baseline",
    category: "Baseline",
    description: "Classical statistical mechanics indicator measuring the rise in Lag-1 Autocorrelation and rolling variance as a dynamical system approaches a fold bifurcation point.",
    parameters: "2",
    latencyMs: 4.5,
    rocAuc: 0.865,
    prAuc: 0.792,
    f1Score: 0.785,
    leadTimeAccuracy: "74.5% (±4.2 mo)",
    architectureDetails: [
      "Rolling window OLS estimation of AR(1) coefficient phi",
      "Kendall tau rank correlation trend significance testing",
      "Zero look-ahead empirical variance tracking",
    ],
    hyperparameters: { window_size: 24, stride: 1, detrending: "Gaussian Kernel / Linear" },
  },
];
